# Generated by Django 4.1.5 on 2023-01-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite', to='blog.article'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='read_later',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_later', to='blog.article'),
        ),
    ]
