# Generated by Django 4.1.5 on 2023-01-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_userprofile_my_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('DSA', 'DSA'), ('CN', 'CN'), ('OS', 'OS'), ('DBMS', 'DBMS'), ('LINUX', 'LINUX'), ('OTHERS', 'OTHERS')], max_length=200),
        ),
    ]
